# Generated by Django 3.2.8 on 2021-10-28 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id_cola', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_us', models.IntegerField(null=True)),
                ('tiempo_max', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comp', models.DateField(null=True)),
                ('numero_tick', models.IntegerField(null=True)),
                ('estado_tick', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_atraccion',
            fields=[
                ('id_tipo_atr', models.IntegerField(primary_key=True, serialize=False)),
                ('nomb_tip_at', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1, null=True)),
                ('nombres_us', models.CharField(max_length=50, null=True)),
                ('appellidos_us', models.CharField(max_length=50)),
                ('fono_us', models.CharField(max_length=12)),
                ('email_us', models.CharField(max_length=30, null=True)),
                ('estatura_us', models.FloatField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasicore.ticket')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasicore.tipo_usuario')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id_atr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_atr', models.CharField(max_length=20, null=True)),
                ('capacidadd_atr', models.IntegerField(null=True)),
                ('descrip_atr', models.CharField(max_length=200, null=True)),
                ('tiempo_medio', models.IntegerField(null=True)),
                ('estatura_min', models.FloatField(null=True)),
                ('cola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasicore.cola')),
                ('tipo_atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasicore.tipo_atraccion')),
            ],
        ),
    ]
