# Generated by Django 3.2.8 on 2021-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasicore', '0003_auto_20211103_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cola',
            name='a',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
