# Generated by Django 3.2.8 on 2021-11-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasicore', '0005_alter_cola_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atraccion',
            name='cola',
        ),
        migrations.RemoveField(
            model_name='cola',
            name='a',
        ),
        migrations.AddField(
            model_name='cola',
            name='atraccion',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='fantasicore.atraccion'),
        ),
        migrations.AddField(
            model_name='cola',
            name='usuario',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='fantasicore.usuario'),
        ),
    ]
