# Generated by Django 3.2.8 on 2021-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasicore', '0007_auto_20211103_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='id_cola',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
