# Generated by Django 3.2.8 on 2021-11-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasicore', '0008_alter_cola_id_cola'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
